name: actions initialize

on: push


jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

  steps:
    - name: Hello World 찍기 # Step에 이름 붙이는 기능
      run: echo "Hello World" # 실행시킬 명령어 작성
      
  - name: 여러 면련어 문장 작성하기
    run: |
      echo "Good"
      echo "Morning"
      
  - name: 작업폴더가 무엇인지 출력
    run: pwd
    
  - name: 작업 폴더 목록 확인
